- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Gowtham, Anitha, Rishi, Kushu"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('Gowtham') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: Gowtham
    ansible.builtin.debug:
      msg: "Course Info: {{ course | dict2items  }}"